Update fuji.py - Intercepting spaces
If a user enters a blank character in the “Source”, “Temp Image Location” or “DMG Destination” fields in Fuji, the system uses
Line 205 self.Hide()
is executed, but the app can no longer be used.

Error:

  File "/Fuji/fuji.py", line 206, in on_continue
    OVERVIEW_WINDOW.update_overview()
  File "/Fuji/fuji.py", line 293, in update_overview
    result = check.execute(PARAMS)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Fuji/checks/free_space.py", line 50, in execute
    destination_free = self._get_free_space(params.destination)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Fuji/checks/free_space.py", line 18, in _get_free_space
    statvfs = os.statvfs(path)
              ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ' '

This behavior is prevented with .stripe().